apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongo-depl
  labels:
    db-type: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongo
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      containers:
        - name: payments-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-srv
spec:
  selector:
    app: payments-mongo
  ports:
    - name: mongo-db
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
